"use strict";

const { readFileSync, writeFileSync } = require("node:fs");
const { join } = require("node:path");

const root = __dirname;
const model = readFileSync(join(root, "model.js"), "utf8").trimEnd();
const plugin = readFileSync(join(root, "plugin.js"), "utf8").trim();

const output = [
  "// SPDX-License-Identifier: MIT",
  "// Copyright (c) 2026 harrisonaedwards",
  "// Generated by build.js from model.js and plugin.js. Do not edit this file directly.",
  model,
  plugin,
  ""
].join("\n\n");

writeFileSync(join(root, "main.js"), output, "utf8");
